# Generated by Django 6.0.2 on 2026-02-24 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('citizen', 'Citizen'), ('government_authority', 'Government Authority'), ('utility_officer', 'Utility Officer'), ('emergency_operator', 'Emergency Operator'), ('worker', 'Worker')], default='citizen', max_length=50),
        ),
    ]
