# Generated by Django 6.0.2 on 2026-02-25 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('citizen', 'Citizen'), ('government_authority', 'Government Authority'), ('utility_officer', 'Utility Officer'), ('emergency_operator', 'Emergency Operator'), ('team_admin', 'Team Admin'), ('worker', 'Worker')], default='citizen', max_length=50),
        ),
    ]
