# Generated by Django 6.0.2 on 2026-02-27 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.AddField(
            model_name='user',
            name='access_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('citizen', 'Citizen'), ('government_authority', 'Government Authority'), ('emergency_operator', 'Emergency Operator'), ('utility_officer', 'Utility Officer'), ('team_admin', 'Team Administrator'), ('worker', 'Worker')], default='citizen', max_length=50),
        ),
    ]
