# Generated by Django 6.0.2 on 2026-02-27 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_user_address_user_access_code_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='access_code',
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True),
        ),
    ]
