# Generated by Django 6.0.2 on 2026-02-27 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_user_access_code_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access_code',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
