# Generated by Django 5.2.7 on 2026-02-27 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='access_code',
        ),
    ]
