# Generated by Django 6.0.2 on 2026-02-13 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0002_alter_emergencyrequest_location_lat_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('ambulance', 'Ambulance'), ('fire_truck', 'Fire Truck'), ('police_car', 'Police Car'), ('rescue_vehicle', 'Rescue Vehicle')], max_length=50)),
                ('vehicle_number', models.CharField(max_length=20, unique=True)),
                ('driver_name', models.CharField(max_length=100)),
                ('driver_contact', models.CharField(max_length=15)),
                ('is_available', models.BooleanField(default=True)),
                ('current_location', models.CharField(blank=True, max_length=200)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['vehicle_type', 'vehicle_number'],
            },
        ),
        migrations.CreateModel(
            name='DispatchRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('en_route', 'En Route'), ('on_scene', 'On Scene'), ('completed', 'Completed')], default='assigned', max_length=20)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispatches_made', to=settings.AUTH_USER_MODEL)),
                ('emergency_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatches', to='emergency.emergencyrequest')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='emergency.emergencyvehicle')),
            ],
        ),
    ]
