# Generated by Django 6.0.2 on 2026-02-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0005_alter_dispatchrecord_id_alter_emergencyrequest_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergencyteam',
            name='description',
        ),
        migrations.AddField(
            model_name='emergencyteam',
            name='equipment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='emergencyteam',
            name='team_type',
            field=models.CharField(choices=[('medical', 'Medical Emergency Response'), ('fire', 'Fire Response'), ('police', 'Police Response'), ('search_rescue', 'Search & Rescue'), ('hazardous_materials', 'Hazardous Materials'), ('water', 'Water Supply Response'), ('electricity', 'Electricity Response'), ('road_maintenance', 'Road Maintenance'), ('garbage', 'Garbage Management'), ('public_works', 'Public Works'), ('special_operations', 'Special Operations')], default='medical', max_length=50),
        ),
    ]
