# Generated by Django 6.0.2 on 2026-02-25 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0006_remove_emergencyteam_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyteam',
            name='team_leader',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'worker'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='emergencyteam',
            name='team_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='emergencyteam',
            name='vehicles',
            field=models.ManyToManyField(related_name='teams', to='emergency.emergencyvehicle'),
        ),
        migrations.AlterField(
            model_name='emergencyteam',
            name='workers',
            field=models.ManyToManyField(limit_choices_to={'role': 'worker'}, related_name='teams', to=settings.AUTH_USER_MODEL),
        ),
    ]
