# Generated by Django 6.0.2 on 2026-02-26 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0003_alter_complaint_id_alter_complaintupdate_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='location_lat',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='location_lng',
        ),
        migrations.RemoveField(
            model_name='utilityteam',
            name='description',
        ),
        migrations.AddField(
            model_name='utilityteam',
            name='team_type',
            field=models.CharField(choices=[('water', 'Water Supply Response'), ('electricity', 'Electricity Response'), ('road_maintenance', 'Road Maintenance'), ('garbage', 'Garbage Management'), ('public_works', 'Public Works'), ('special_operations', 'Special Operations')], default='water', max_length=50),
        ),
        migrations.AlterField(
            model_name='utilityteam',
            name='team_leader',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'worker'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_utility_teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='utilityteam',
            name='team_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='utilityteam',
            name='workers',
            field=models.ManyToManyField(limit_choices_to={'role': 'worker'}, related_name='utility_teams', to=settings.AUTH_USER_MODEL),
        ),
    ]
