# Generated by Django 6.0.2 on 2026-02-26 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0007_alter_emergencyteam_team_leader_and_more'),
        ('utilities', '0005_complaint_location_lat_complaint_location_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilityteam',
            name='vehicles',
            field=models.ManyToManyField(blank=True, related_name='utility_teams', to='emergency.emergencyvehicle'),
        ),
    ]
